### PR TITLE
grey out start button, fix remember me bug

### LINKED ISSUE #116: Only allow user to take survey if we intend them to

### LINKED ISSUE #176: gray out start survey button if user shouldnt take survey now

### PR DESCRIPTION
**Pull request by daking2014**
@tiffanyfong @hmc-cs-asheppard @hmc-cs-dlan 
close #116 close #176

### CODE REVIEW

File: PaWPal/PaWPal/DatabaseController.swift [hunk 1]
```diff
@@ -155,6 +155,14 @@ class DatabaseController {
         return AppState.sharedInstance.totalSurveyCount
     }
     
+    static func getClosestNotification() -> String {
+        return AppState.sharedInstance.closestScheduledNotification!
```
Comment (tiffanyfong) [inline PaWPal/PaWPal/DatabaseController.swift:159]: does unwrapping always work? when will this ever be a nil value?

Comment (daking2014) [reply PaWPal/PaWPal/DatabaseController.swift:159]: not if AppState is being loaded properly
